orbs:
  gcp-gcr: circleci/gcp-gcr@0.7.1

version: 2.1

jobs:
  test:
    docker:
      - image: mozilla/cidockerbases:docker-latest
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build image
          command: make build
      - run:
          name: Test Code
          command: make test
      - run:
          name: Lint
          command: make lint

workflows:
  version: 2
  public-data-report-etl-build:
    jobs:
      - test:
          filters:
            tags:
              only: /.*/
      - gcp-gcr/build-and-push-image:
          context: data-eng-airflow-gcr
          image: firefox-public-data-report-etl
          filters:
            branches:
              only: main
